### ISSUE TITLE
Could not find gem jekyll-remote_csv

### ISSUE THREAD

**Issue by miguelcarvajal** [everypolitician/jekyll-remote_csv#7]
Hi, @chrismytton 

I am trying to install the gem but It appears to not be uploaded to RubyGems. Do you know if there is any problem? Am I doing something wrong? I am trying to install the gem into my Jekyll project.

`Could not find gem 'jekyll-remote_csv (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.`

Thanks!

**Comment by chrismytton** [comment]
Hi @miguelcarvajal! I've just released version 0.1.0 to Rubygems, so you should be able to install it now. I hadn't released it before because it's a bit of a work in progress, so if you find any rough edges or confusing parts please do open a ticket!

**Comment by miguelcarvajal** [comment]
Thanks!
